SELECT ?a WHERE {
   {
      <{companyURI1}> ?a <{companyURI2}> .
   } UNION
   {
      <{companyURI2}> ?a <{companyURI1}> .
   } .
   FILTER(?a != rdf:type && ?a !=<http://dbpedia.org/ontology/wikiPageWikiLink>).
}